[tool.poetry]
name = "cookiecutter-project"
version = "0.1.0"
description = ""
authors = ["Gnonpi <legnonpi@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
cookiecutter = "^2.1.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
